### ISSUE TITLE
XMLRequestException raised on all queries

### ISSUE THREAD

**Issue by ksymilian** [seibert-media/Highton#10]
Hey!
I keep getting the XMLRequestException after calling any of the get_-methods (i.e. get_companies())
` File "/usr/local/lib/python3.4/dist-packages/highton/highton.py", line 321, in get_companies
    self._get_paged_data('companies'), Company)
  File "/usr/local/lib/python3.4/dist-packages/highton/highton.py", line 139, in _get_paged_data
    self._get_request(endpoint, params).content
  File "/usr/local/lib/python3.4/dist-packages/highton/highton.py", line 48, in _get_request
    raise XMLRequestException(url)
highton.custom_exceptions.XMLRequestException: https://somename.highrisehq.com/companies.xml`

Same error with Python 2.7 and 3. I'd appreciate any help - thanks!

**Comment by ksymilian** [comment]
Error was due to an expired api token. my bad.

**Comment by bykof** [comment]
Oh sorry, 
I didn't see your email. Okay its good that the fault is not in the API :D 
Have a nice day!
